/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RehomeRouteImport } from './routes/rehome'
import { Route as LearnMoreRouteImport } from './routes/learn-more'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AnimalsIdRouteImport } from './routes/animals.$id'
import { Route as AdminMedicalRouteImport } from './routes/admin.medical'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdoptionRouteImport } from './routes/admin.adoption'
import { Route as AdminTableTableRouteImport } from './routes/admin.table.$table'

const RehomeRoute = RehomeRouteImport.update({
  id: '/rehome',
  path: '/rehome',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnMoreRoute = LearnMoreRouteImport.update({
  id: '/learn-more',
  path: '/learn-more',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIdRoute = AnimalsIdRouteImport.update({
  id: '/animals/$id',
  path: '/animals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMedicalRoute = AdminMedicalRouteImport.update({
  id: '/admin/medical',
  path: '/admin/medical',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdoptionRoute = AdminAdoptionRouteImport.update({
  id: '/admin/adoption',
  path: '/admin/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTableTableRoute = AdminTableTableRouteImport.update({
  id: '/admin/table/$table',
  path: '/admin/table/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/learn-more': typeof LearnMoreRoute
  '/rehome': typeof RehomeRoute
  '/admin/adoption': typeof AdminAdoptionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medical': typeof AdminMedicalRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/table/$table': typeof AdminTableTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/learn-more': typeof LearnMoreRoute
  '/rehome': typeof RehomeRoute
  '/admin/adoption': typeof AdminAdoptionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medical': typeof AdminMedicalRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/table/$table': typeof AdminTableTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/learn-more': typeof LearnMoreRoute
  '/rehome': typeof RehomeRoute
  '/admin/adoption': typeof AdminAdoptionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medical': typeof AdminMedicalRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/table/$table': typeof AdminTableTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/learn-more'
    | '/rehome'
    | '/admin/adoption'
    | '/admin/login'
    | '/admin/medical'
    | '/animals/$id'
    | '/admin/'
    | '/admin/table/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/learn-more'
    | '/rehome'
    | '/admin/adoption'
    | '/admin/login'
    | '/admin/medical'
    | '/animals/$id'
    | '/admin'
    | '/admin/table/$table'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/learn-more'
    | '/rehome'
    | '/admin/adoption'
    | '/admin/login'
    | '/admin/medical'
    | '/animals/$id'
    | '/admin/'
    | '/admin/table/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  LearnMoreRoute: typeof LearnMoreRoute
  RehomeRoute: typeof RehomeRoute
  AdminAdoptionRoute: typeof AdminAdoptionRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMedicalRoute: typeof AdminMedicalRoute
  AnimalsIdRoute: typeof AnimalsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTableTableRoute: typeof AdminTableTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rehome': {
      id: '/rehome'
      path: '/rehome'
      fullPath: '/rehome'
      preLoaderRoute: typeof RehomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-more': {
      id: '/learn-more'
      path: '/learn-more'
      fullPath: '/learn-more'
      preLoaderRoute: typeof LearnMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$id': {
      id: '/animals/$id'
      path: '/animals/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AnimalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/medical': {
      id: '/admin/medical'
      path: '/admin/medical'
      fullPath: '/admin/medical'
      preLoaderRoute: typeof AdminMedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adoption': {
      id: '/admin/adoption'
      path: '/admin/adoption'
      fullPath: '/admin/adoption'
      preLoaderRoute: typeof AdminAdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/table/$table': {
      id: '/admin/table/$table'
      path: '/admin/table/$table'
      fullPath: '/admin/table/$table'
      preLoaderRoute: typeof AdminTableTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  LearnMoreRoute: LearnMoreRoute,
  RehomeRoute: RehomeRoute,
  AdminAdoptionRoute: AdminAdoptionRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMedicalRoute: AdminMedicalRoute,
  AnimalsIdRoute: AnimalsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTableTableRoute: AdminTableTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
